name: abi export removal
description: remove abi exports for wifi and bt functionality

runs:
 using: composite
 steps:
  - name: remove protected exports
    shell: bash
    run: |
     cd "$CONFIG"
     if [[ -d kernel_platform ]]; then
      rm -rf ./kernel_platform/common/android/abi_gki_protected_exports_*
      rm -rf ./kernel_platform/msm-kernel/android/abi_gki_protected_exports_*
     else
      rm -rf "$COMMON"/android/abi_gki_protected_exports_*
     fi

     #remove protected exports from build.bazel file
     cd ..
     cd "$COMMON"
     perl -pi -e 's/^\s*"protected_exports_list"\s*:\s*"android\/abi_gki_protected_exports_aarch64",\s*$//;' ./BUILD.bazel
