name: abi export removal
description: remove abi exports for wifi and bt functionality

runs:
 using: composite
 steps:
  - name: remove protected exports
    shell: bash
    run: |
     cd "$COMMON"
     
     rm -rf ./android/abi_gki_protected_exports_*
     perl -pi -e 's/^\s*"protected_exports_list"\s*:\s*"android\/abi_gki_protected_exports_aarch64",\s*$//;' ./BUILD.bazel
