name: Add bbg
description: add and enable bbg into the kernel

runs:
  using: composite
  steps:
   - name: add bbg into kernel
     shell: bash
     run: |
      cd "$COMMON"
      echo "Adding BBG..."
      curl -LSs https://github.com/vc-teahouse/Baseband-guard/raw/main/setup.sh | bash
      
   - name: enable bbg in defconfig
     shell: bash
     run: |
      cd "$GITHUB_WORKSPACE"
      cat >> "$GKI_DEFCONFIG" << 'EOF'
      CONFIG_BBG=y
      EOF

   - name: add bbg into kconfig
     shell: bash
     run: |
       cd "$COMMON"
       sed -i '/^config LSM$/,/^help$/{ /^[[:space:]]*default/ { /baseband_guard/! s/selinux/selinux,baseband_guard/ } }' security/Kconfig

   - name: if config_lsm is in defconfig, add bbg
     shell: bash
     run: |
      cd "$GITHUB_WORKSPACE"
      sed -i '/^CONFIG_LSM=/ s/"$/,baseband_guard"/' "$GKI_DEFCONFIG"
