name: add ntsync
description: integrate ntsync into kernel
inputs:
  android_version:
    description: 'Android version (android14)'
    required: true
  kernel_version:
    description: 'Kernel version (6.1)'
    required: true

runs:
  using: composite
  steps:
   - name: apply ntsync patches
     shell: bash
     run: |
      cd "$COMMON"
      patch -p1 < "$KERNEL_PATCHES/common/ntsync/ntsync_base.patch"
      patch -p1 < "$KERNEL_PATCHES/common/ntsync/ntsync_compat_${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch"
      
   - name: enable ntsync config
     shell: bash
     run: |
      cat >> "$GKI_DEFCONFIG" << 'EOF'
      CONFIG_NTSYNC=y
      EOF
