name: 'Download Samsung Kernels'
description: "initialize and download the samsung kernel"

inputs:
  branch:
    description: 'Device Kernel branch'
    required: true

runs:
 using: composite
 steps:
   - name: Clone Kernel Source
     shell: bash
     run: |
      if [[ "${{ inputs.branch }}" == "SM8450-Kleenn-S22" ]]; then
        echo "🚀 检测到定制设备，正在开启极速浅克隆拉取外壳..."
        # 拉取你本人的外壳仓库及当前指针指向的子模块
        git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/kleenn/android_kernel_samsung_sm8450_s22.git $CONFIG
        
        # 👑 【造物主权限：动态追尾机制】
        # 无视外壳仓库的旧指针，强行将 common 子模块拉扯到你修改后的 main 分支最前沿！
        echo "🔄 强制同步子模块至 main 分支的最前沿..."
        cd $CONFIG
        git submodule update --remote --depth 1 kernel_platform/common
        
      else
        echo "📥 正在从 WildKernels 拉取常规源码..."
        git clone --depth 1 -b ${{ inputs.branch }} --single-branch https://github.com/WildKernels/Samsung_Kernels.git $CONFIG
      fi
